In [2]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.ensemble import GradientBoostingClassifier 
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, r2_score, accuracy_score, f1_score, roc_auc_score
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from xgboost import XGBRegressor, XGBClassifier

In [3]:
df = pd.read_csv('f1_results_2017_2025.csv')

In [4]:
df.head()

,season_year,race_round_number,race_name,race_date,circuit_name,driver_name,driver_nationality,constructor_name,grid_position,final_position,points,laps_completed,race_time,fastest_lap,status
0,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Sebastian Vettel,German,Ferrari,2,1,25.0,57,1:24:11.672,1:26.638,Finished
1,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Lewis Hamilton,British,Mercedes,1,2,18.0,57,+9.975,1:27.033,Finished
2,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Valtteri Bottas,Finnish,Mercedes,3,3,15.0,57,+11.250,1:26.593,Finished
3,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Kimi Räikkönen,Finnish,Ferrari,4,4,12.0,57,+22.393,1:26.538,Finished
4,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Max Verstappen,Dutch,Red Bull,5,5,10.0,57,+28.827,1:26.964,Finished

In [5]:
df['final_position'] = pd.to_numeric(df['final_position'], errors='coerce')

In [6]:
df

,season_year,race_round_number,race_name,race_date,circuit_name,driver_name,driver_nationality,constructor_name,grid_position,final_position,points,laps_completed,race_time,fastest_lap,status
0,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Sebastian Vettel,German,Ferrari,2,1,25.0,57,1:24:11.672,1:26.638,Finished
1,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Lewis Hamilton,British,Mercedes,1,2,18.0,57,+9.975,1:27.033,Finished
2,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Valtteri Bottas,Finnish,Mercedes,3,3,15.0,57,+11.250,1:26.593,Finished
3,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Kimi Räikkönen,Finnish,Ferrari,4,4,12.0,57,+22.393,1:26.538,Finished
4,2017,1,Australian Grand Prix,2017-03-26,Albert Park Grand Prix Circuit,Max Verstappen,Dutch,Red Bull,5,5,10.0,57,+28.827,1:26.964,Finished
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3653,2025,14,Hungarian Grand Prix,2025-08-03,Hungaroring,Esteban Ocon,French,Haas F1 Team,17,16,0.0,69,+45.258,1:21.916,Lapped
3654,2025,14,Hungarian Grand Prix,2025-08-03,Hungaroring,Yuki Tsunoda,Japanese,Red Bull,20,17,0.0,69,+46.943,1:21.180,Lapped
3655,2025,14,Hungarian Grand Prix,2025-08-03,Hungaroring,Franco Colapinto,Argentine,Alpine F1 Team,14,18,0.0,69,+47.370,1:20.827,Lapped
3656,2025,14,Hungarian Grand Prix,2025-08-03,Hungaroring,Pierre Gasly,French,Alpine F1 Team,16,19,0.0,69,+56.344,1:21.433,Lapped
3657,2025,14,Hungarian Grand Prix,2025-08-03,Hungaroring,Oliver Bearman,British,Haas F1 Team,11,20,0.0,48,NaN,1:21.989,Retired

In [7]:
df = df.drop(columns=['race_time'],inplace=True)